---
title: "Tree Diversity Effects"
author: "collnell"
date: "July 5, 2016"
output: 
  html_document:
    toc: yes
    toc_depth: 3
    toc_float: true
    theme: flatly
    highlight: tango
    fig_caption: true
    code_folding: hide
---


```{r setup, include=FALSE}
library(shiny)
library(ggplot2)
library(ggthemes)
library(reshape2)
library(plotly)
library(dplyr)
library(flexdashboard)
###enter data
birds<-read.csv("/Users/colleennell/Documents/R/enemies/enemy_bird_visit.csv")
sp.list<-read.csv("/Users/colleennell/Documents/R/enemies/enemy_bird_list.csv")
```

```{r,datasummary}
std <- function(x) sd(x)/sqrt(length(x))

##clean data 
drops<-c("Grand.Total","X.blank.")##clean up df
birds=birds[,!(names(birds) %in% drops)]
birds[is.na(birds)]<-0
cols<-names(birds)
drops<-c("DIVERSITY","PLOT","VISIT")
sps<-cols[-c(1:3)]##this is a list of the names of the birds only
birds$VISIT<-as.character(birds$VISIT)
birds$total_abun<-rowSums(birds[,sps])
##summarize data for plots/analyses
#by plot
#abundance
bird.plot<-birds%>%
  mutate(birds_plot_visit=rowSums(.[sps]))%>%
  group_by(DIVERSITY,PLOT)%>%
  summarize(total_birds_plot=sum(birds_plot_visit),
            n_visit=length(VISIT),
            mean_birds_visit=mean(birds_plot_visit),
            se_birds_visit=std(birds_plot_visit),
            birds_30=mean_birds_visit*3,
            se_30=std(birds_plot_visit)*3)





```

  

```{r}

abun_by_plot<-ggplot(bird.plot,aes(x=reorder(PLOT,birds_30),y=birds_30),fill=DIVERSITY)+
  geom_bar(stat="identity")+
  labs(x="Plot",y="Birds/30/plot")
abun_by_plot
plot_diff_abun<-aov(total_abun~PLOT+VISIT,data=birds)
summary(plot_diff_abun)##bird abundance varies by plot

```



```{r}
bird.div<-bird.plot%>%
  group_by(DIVERSITY)%>%
  summarize(total_birds_div=sum(total_birds_plot),
            n_plots=length(PLOT),
            mean_birds_plot_30=mean(birds_30),
            se_birds_plot_30=std(birds_30),
            mean_birds_plot_visit=sum(total_birds_plot)/sum(n_visit),
            se_birds_plot_visit=std(total_birds_plot))

abun_by_div<-aov(mean_birds_visit~DIVERSITY,data=bird.plot)##plot is replicate
summary(abun_by_div)
```
<br>  
```{r,fig.height=4, fig.width=3}
div_abun_plot<-ggplot(bird.div,aes(x=DIVERSITY,y=mean_birds_plot_30,color=DIVERSITY))+
  geom_point(size=10,shape=1)+
  geom_errorbar(aes(ymin=mean_birds_plot_30-se_birds_plot_30,ymax=mean_birds_plot_30+se_birds_plot_30),color="black",width=.1)+
  labs(x="Tree Diversity",y="Birds/30/plot")+
  theme_minimal()+
  theme(legend.position="none")
div_abun_plot+geom_point(data=bird.plot,aes(x=DIVERSITY,y=birds_30),size=2)
```