---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE,}
library(flexdashboard)

std <- function(x) sd(x)/sqrt(length(x))
```

```{r, birddata, comment=F,message=F,warning=F,echo=F}
birds<-read.csv("/Users/colleennell/Documents/R/enemies/enemy_bird_visit.csv")
drops<-c("Grand.Total","X.blank.")##clean up df
birds=birds[,!(names(birds) %in% drops)]
birds[is.na(birds)]<-0
cols<-names(birds)
drops<-c("DIVERSITY","PLOT","VISIT")
sps<-cols[-c(1:3)]##this is a list of the names of the birds only


```
Sidebar {.sidebar}  
===================================
  
words here?!?!
  

Column {data-width=650}
-----------------------------------------------------------------------

### Abundance
```{r,bird_abundance,echo=F,message=F}
abun.by.plot<-birds%>%
  mutate(abun = rowSums(.[sps]))%>%
  group_by(DIVERSITY,PLOT)%>%
  summarize(mean_abun=mean(abun),se_abun=std(abun))

abun.by.div<-abun.by.plot%>%
  group_by(DIVERSITY)%>%
  summarize(abun_div=mean(mean_abun),se_div=std(mean_abun))

abun.div.plot<-ggplot(abun.by.div,aes(x=DIVERSITY,y=abun_div,fill=DIVERSITY))+
  geom_bar(stat="identity")+geom_errorbar(aes(ymin=abun_div-se_div,ymax=abun_div+se_div),width=.2)+theme_minimal()+labs(x="Tree Diversity",y="Bird Abundance")

abun.div.plot

```

```{r}

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

