---
title: "Effects of Tree Diversity to Insectivorous Birds"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    theme: flatly
---
```{r}
library(dplyr)
library(reshape2)
library(vegan)
library(ggplot2)

std <- function(x) sd(x)/sqrt(length(x))
```

```{r, birddata, comment=F,message=F,warning=F,echo=F}
birds<-read.csv("/Users/colleennell/Documents/R/enemies/enemy_bird_visit.csv")
drops<-c("Grand.Total","X.blank.")##clean up df
birds=birds[,!(names(birds) %in% drops)]
birds[is.na(birds)]<-0
cols<-names(birds)
drops<-c("DIVERSITY","PLOT","VISIT")
sps<-cols[-c(1:3)]##this is a list of the names of the birds only

sp.list<-read.csv("/Users/colleennell/Documents/R/enemies/enemy_bird_list.csv")
```

```{r,birdtotals}
bird.totals<-birds%>%
  mutate(birds_plot_visit=rowSums(.[sps]))%>%
  group_by(DIVERSITY,PLOT)%>%
  summarize(total_birds_plot=sum(birds_plot_visit),
            n_visit=length(VISIT),
            mean_birds_visit=mean(birds_plot_visit),
            se_birds_visit=std(birds_plot_visit),
            birds_30=mean_birds_visit*3,
            se_30=std(birds_plot_visit)*3)

birds$VISIT<-as.character(birds$VISIT)
birds$total_abun<-rowSums(birds[,sps])

bird.div<-bird.totals%>%
  group_by(DIVERSITY)%>%
  summarize(total_birds_div=sum(total_birds_plot),
            n_plots=length(PLOT),
            mean_birds_plot_30=mean(birds_30),
            se_birds_plot_30=std(birds_30),
            mean_birds_plot_visit=sum(total_birds_plot)/sum(n_visit),
            se_birds_plot_visit=std(total_birds_plot))

poly<-birds%>%
  filter(DIVERSITY=='P')%>%
  group_by(DIVERSITY,PLOT)%>%
  select(-VISIT)%>%
  summarize_each(funs(sum))
poly.birds<-poly[,sps]
##same for monoculture plots
mono<-birds%>%
  filter(DIVERSITY=='M')%>%
  group_by(DIVERSITY,PLOT)%>%
  select(-VISIT)%>%
  summarize_each(funs(sum))
mono.birds<-mono[,sps]

birds.by.plot<-rbind(poly,mono)
bb.plot<-birds.by.plot[,sps]
birds.by.plot$plot.diversity<-diversity(bb.plot)##calculate diversity by plot
##evenness
birds.by.plot$plot.evenness<-birds.by.plot$plot.diversity/log(specnumber(bb.plot))

div<-left_join(bird.div

div$evenness<-
div$diversity
div$abundance
div$richness

plot$evenness<-
plot$diversity<-
plot$abundance<-
plot$richness<-
  
 
 
metric<-reactive({
  div<-df[,input$bird.metric] ##these are the response variables
  plot<- #by plot
})

div.plot<-ggpot(div,aes(x=DIVERSITY,y=))

```

```{r,guilddata,warning=F}
##use sp.list data with bird data to regroup species into feeding guilds
bird.melt<-melt(birds[,-1],value.name="abundance",id.var=c("PLOT","VISIT"))
birds.guilds<-dcast(bird.melt,variable+VISIT~PLOT,value.var="abundance")%>%
  rename(ID = variable)%>%
  left_join(sp.list[,c('feeding.guild','ID')],birds.transp,by="ID")%>%
  select(-ID)%>%
  group_by(feeding.guild,VISIT)%>%
  summarize_each(funs(sum))

guild.summ<-melt(birds.guilds,value.name="abundance",id.var=c("feeding.guild","VISIT"))%>%
  rename(PLOT = variable)%>%
  dcast(feeding.guild+VISIT~PLOT,value.var="abundance")%>%
  group_by(feeding.guild)%>%
  summarize_each(funs(mean(.,na.rm=TRUE)))%>%
  select(-VISIT)%>%
  mutate(mean_birds_plot=rowMeans(.[,-1]),total_birds_plot=rowSums(.[,-1]))%>%
  select(feeding.guild,mean_birds_plot,total_birds_plot)%>%
  mutate(n_30 = mean_birds_plot*3)%>%
  mutate(n_30 = mean_birds_plot*3, per_total = mean_birds_plot/sum(mean_birds_plot))
```


Bird Observations 
===================================== 

Inputs {.sidebar} 
-------------------------------------
All birds
Insectivorous birds

Species Diversity
Mahogany- Genetic Diversity

```{r}
selectInput('bird.metric',label='Bird Community',choices=c('abundance','diversity','evennes','richness'))




```
    
Row {data-height=400}
-------------------------------------
    
### Bird Diversity  

```{r}
abun_by_plot<-ggplot(bird.totals,aes(x=reorder(PLOT,birds_30),y=birds_30,fill=DIVERSITY))+
  geom_bar(stat="identity")+
  geom_errorbar(aes(ymin=birds_30-se_30,ymax=birds_30+se_30))+
  labs(x="Plot",y="Birds/30/plot")
abun_by_plot



```
   
Row {data-height=500,data-width=500}
-------------------------------------
    
### Bird Abundance   
<br>  
    ```{r,bird_abundance,echo=F,fig.height=3,fig.width=3}

div_abun_plot<-ggplot(bird.div,aes(x=DIVERSITY,y=mean_birds_plot_30,color=DIVERSITY))+
  geom_point(size=8,shape=1)+
  geom_errorbar(aes(ymin=mean_birds_plot_30-se_birds_plot_30,ymax=mean_birds_plot_30+se_birds_plot_30),color="black",width=.1)+
  labs(x="Tree Diversity",y="Birds/30/plot")+
  theme_minimal()+
  theme(legend.position="none")
div_abun_plot+geom_point(data=bird.totals,aes(x=DIVERSITY,y=birds_30),size=1)
```   
<br>  
```{r}
abun_by_div<-aov(mean_birds_visit~DIVERSITY,data=bird.totals)##plot is replicate
summary(abun_by_div)
```
Row {data-height=500}  
------------------------------------
###Shannon Diversity  

```{r,shannondiv,fig.height=3,fig.width=3}
div_shan<-aov(plot.diversity~DIVERSITY,data=birds.by.plot)
summary(div_shan)#yes

shan_plot<-ggplot(birds.by.plot,aes(x=DIVERSITY,y=plot.diversity,color=DIVERSITY))+
  geom_point(size=10,shape=1)+labs(x="Tree Diversity",y="Shannon Diversity")+
  theme_minimal()+
  theme(legend.position="none")
shan_plot
```
<br>  

Row {data-height=500}  
------------------------------------  

### Summary
  
`r length(unique(sps))` species observed  
`r sum(bird.totals$total_birds_plot)` individuals observed   
`r (mean(bird.totals$birds_30*2))` birds/hr/plot  

```{r,fig.width=5,fig.height=5}
guild.pie<-ggplot(guild.summ,aes())

```

Site Information 
===================================== 

Inputs {.sidebar} 
-------------------------------------
WORDS 
    
Row {data-height=400}
-------------------------------------
    
### Interactive map of UADY diversity plots  
1 plot = 441 m2
```{r}

```
   
Row {data-height=500,data-padding=10}
-------------------------------------
    
### Annual variation of insectivorous birds in Yucatan, Mexico  
    ```{r,bird_abundfce,echo=F,message=F,fig.width=5,fig.height=3}
abun.by.plot<-birds%>%
  mutate(abun = rowSums(.[sps]))%>%
  group_by(DIVERSITY,PLOT)%>%
  summarize(mean_abun=mean(abun),se_abun=std(abun))

abun.by.div<-abun.by.plot%>%
  group_by(DIVERSITY)%>%
  summarize(abun_div=mean(mean_abun),se_div=std(mean_abun))

abun.div.plot<-ggplot(abun.by.div,aes(x=DIVERSITY,y=abun_div,fill=DIVERSITY))+
  geom_bar(stat="identity")+geom_errorbar(aes(ymin=abun_div-se_div,ymax=abun_div+se_div),width=.2)+theme_minimal()+labs(x="Tree Diversity",y="Bird Abundance")+theme(legend.position="top")

abun.div.plot

```    
```{r}

```
    
### Chavfv

```{r}

```

